import {territoryPage} from './territory.mjs';
import {source,link,request,section,details} from './pages.mjs';
const products=[
 ['albicocche','Confettura di albicocche','confetture','160 g','€ 4','Albicocche biologiche, zucchero e limone. Frutta: almeno 75 g ogni 100 g. La scheda segnala possibili tracce di frutta a guscio.','confettura-extra-albicocche/'],
 ['pera','Confettura di Pera Signora','confetture','160 g','€ 6','Il sapore della Pera Signora, produzione tradizionale valorizzata dal Presidio Slow Food.','confettura-extra-pera/'],
 ['prugne','Confettura di prugne','confetture','160 g','€ 3,50','Prugne biologiche, zucchero e limone. Frutta: almeno 75 g ogni 100 g.','confettura-extra-prugne/'],
 ['fichi','Confettura di fichi','confetture','160 g','€ 4','Fichi, zucchero e limone. Frutta: almeno 75 g ogni 100 g.','confettura-extra-fichi/'],
 ['fragole','Confettura di fragole Candonga','confetture','160 g','€ 6','Fragole Candonga del Metapontino, zucchero e limone. Frutta: almeno 75 g ogni 100 g.','confettura-extra-fragole/'],
 ['melone','Confettura di melone','confetture','160 g','€ 6','Melone, zucchero e limone. Frutta: almeno 75 g ogni 100 g.','confettura-extra-melone/'],
 ['lamponi','Confettura di lamponi','confetture','160 g','€ 6','La confettura di lamponi completa la selezione di conserve dolci dell’azienda.','confettura-extra-lamponi/'],
 ['arance','Marmellata di arance','confetture','160 g','€ 4','Arance biologiche, zucchero e limone. Frutta: almeno 75 g ogni 100 g.','marmellata-arance/'],
 ['passata','Passata di pomodoro','passate','500 g','€ 4','Pomodori Mini San Marzano e Datterino, sale e basilico. La scheda presenta anche il formato da 1 kg, da richiedere.','passata-pomodoro/'],
 ['pomodorini','Passata con pomodorini di collina','passate','500 g','€ 5','Pomodorini in passata al naturale, sale e basilico: un ingrediente della ricetta dei frizzuli.','passata-pomodorini-collina/'],
 ['miele','Miele di fiori d’arancio','miele','250 g','€ 5','Miele di agrumi, da gustare sul pane e nella merenda della fattoria. Conservare lontano dal calore.','miele-arancio/'],
 ['semola','Semola Senatore Cappelli','farina','1 kg','€ 4','Grano duro per la pasta e le preparazioni di casa. Per le sementi biologiche contatta l’azienda.','grano-cappelli/'],
 ['olio','Olio extravergine biologico','olio','750 ml / 2 l / 5 l','€ 30 / 50 / 100','Bottiglia da 750 ml oppure latte da 2 e 5 litri. Chiedi disponibilità e annata della produzione.','olio-extravergine-oliva/']
];
const catalog=`<div class="product-filters" role="group" aria-label="Filtra i prodotti">${[['all','Tutto'],['confetture','Confetture'],['passate','Passate'],['miele','Miele'],['olio','Olio'],['farina','Semola']].map(([key,label],i)=>`<button type="button" data-product-filter="${key}" aria-pressed="${i===0}">${label}</button>`).join('')}</div><p class="micro product-count" role="status" data-product-count>13 prodotti</p><div class="product-list">${products.map(([id,title,cat,size,price,desc,path],i)=>`<details id="${id}" data-product-category="${cat}"><summary><span class="micro">${String(i+1).padStart(2,'0')}</span><span class="product-name">${title}<small>${size}</small></span><span class="product-price">${price}</span><span aria-hidden="true">+</span></summary><div><p>${desc}</p>${source(`prodotti-tipici/${path}`,'Scheda del prodotto')}${request('Prodotti tipici','Chiedi questo prodotto')}</div></details>`).join('')}</div>`;
export const discoverPages=[
 {file:'prodotti.html',label:'Prodotti',eyebrow:'La dispensa del Pago',title:'Le stagioni,<br>da portare <em>via.</em>',description:'Tutti i prodotti Il Pago: confetture, marmellata, passate, miele, semola e olio biologico. Formati, prezzi pubblicati e richieste dirette.',intro:'Un vasetto aperto a colazione. Un filo d’olio sul pane. Piccoli gesti che sanno ancora di vacanza.',image:'preserves',alt:'Vasetti di confetture e marmellate prodotti da Il Pago',sections:[
 section('dispensa','01 / Dalla nostra terra','Il raccolto<br>diventa <em>ricordo.</em>',`<p>La frutta viene lavorata a maturazione, seguendo la stagione. Nel laboratorio aziendale si preparano confetture e marmellate con metodi tradizionali, senza aggiungere conservanti o pectina.</p>${link('il-pago.html#azienda','Conosci l’azienda agricola')}${source('prodotti-tipici/','Produzione e laboratorio')}`),
 section('catalogo','02 / La selezione','Cose <em>buone.</em>',`<p class="catalog-note">Prezzi pubblicati da Il Pago, consultati il 13 settembre 2026. Disponibilità, consegna e totale vengono confermati dall’azienda prima dell’acquisto.</p>${catalog}`),
 section('acquisto','03 / Dalla dispensa a casa','Scegli.<br>Al resto <em>pensiamo insieme.</em>',`<p>Indica i prodotti e le quantità nella richiesta. Puoi chiedere informazioni sul programma di consegna a domicilio DAYVIVERI per frutta e verdura a km zero: zone servite, costi e disponibilità vanno concordati.</p><p>Per ingredienti e allergeni fai riferimento all’etichetta del prodotto acquistato. Per le confetture indicate in scheda, dopo l’apertura è prevista conservazione in frigorifero e consumo entro sette giorni; per le passate, entro quattro o cinque giorni.</p>${request('Prodotti tipici','Prepara la tua richiesta')}${source('prodotti-tipici/','Produzione e consegna DAYVIVERI')}`)
 ],next:['contatti.html','Chiedi i prodotti del Pago.']},
 territoryPage,
 {file:'soggiorni.html',label:'Proposte di soggiorno',eyebrow:'Un motivo per ritrovarsi',title:'Il tempo<br>che <em>scegli.</em>',description:'Le proposte Il Pago per famiglie, mare, cicloturismo ed enogastronomia. Programmi stagionali, archivio e disponibilità da concordare.',intro:'Una piccola vacanza può avere molte forme. Scegli la tua e raccontaci quando vorresti partire.',image:'garden-evening',alt:'Il giardino di Il Pago illuminato per la sera',sections:[
 section('famiglie','01 / Mare e campagna','Le vacanze<br><em>insieme.</em>',`<p>La proposta estiva 2026 unisce soggiorno, ristorante, fattoria e giardino con giochi. Per settembre il sito pubblica riduzioni dal 5% al 15% in base alla durata; la quota comprende pernottamento, biancheria, consumi e riassetto.</p><p>La proposta prevede agevolazioni per bambini: 0–2 anni gratuiti, 3–12 anni con riduzione del 30%. Chiedi un preventivo per verificare importi, combinazioni e disponibilità nelle tue date.</p>${request('Soggiorno','Richiedi la proposta per la tua famiglia')}${source('offerte/estate/','Programma estivo 2026 e condizioni')}`),
 section('sapori','02 / Tra vigna e tavola','Un weekend<br>da <em>assaporare.</em>',`<p>La proposta enogastronomica comprende una visita a vigneti e cantina di Masseria Battifarano, con degustazione di tre vini e taralli locali, per circa un’ora e mezza.</p><p>Il programma prevede soggiorni di due, tre o quattro notti in mezza pensione. Le quote partono rispettivamente da € 145, € 185 e € 229 a persona; per i bambini sono previste riduzioni. Date, condizioni e disponibilità vanno confermate con Il Pago.</p>${request('Esperienze di gusto','Chiedi il weekend enogastronomico')}${source('offerte/week-end-wine/','Programma enogastronomico completo')}`),
 section('attivita','03 / Il tuo ritmo','Muoversi.<br><em>Scoprire.</em>',`<p>Puoi organizzare il soggiorno attorno alla fattoria, alle passeggiate a cavallo con Scuderia 34, al percorso trail o alle escursioni in bicicletta.</p>${link('esperienze.html','Tutte le esperienze')}${link('territorio.html','I luoghi da visitare')}`),
 section('archivio','04 / Storie da ritrovare','Le occasioni<br>da <em>ricordare.</em>',`${details('Sapori e Mani in Pasta · 16–18 gennaio 2026',`<p>Programma trascorso: festa del Fuoco di Sant’Antonio a Rotondella, corso pratico di cucina di circa tre ore e cena con i piatti preparati. Il pacchetto comprendeva due notti, due colazioni, un pranzo e una cena con degustazione.</p><p>Per partecipare a un prossimo corso, chiedi se sono previste nuove date.</p>${request('Esperienze di gusto','Chiedi le prossime date')}${source('offerte/corso-cucina/','Consulta il programma di gennaio 2026')}`)}${details('Ponte del 2 giugno · proposta stagionale',`<p>La proposta pubblicata riguarda pernottamento e colazione, con soggiorni da due a quattro notti e possibilità di prenotare il servizio spiaggia presso un lido convenzionato. Il ponte di quest’anno è trascorso: contattaci per conoscere i programmi futuri.</p>${source('offerte/2giugno/','Consulta la proposta del 2 giugno')}`)}<p class="catalog-note">Programmi consultati il 13 settembre 2026. La richiesta di informazioni non costituisce una prenotazione confermata.</p>`)
 ],next:['ospitalita.html','Trova il tuo rifugio.']}
];
