import {recipes,recipeUrl,recipeIndex} from './recipes.mjs';
const source=(path,label='Approfondisci sul sito ufficiale')=>`<a class="source-link" href="https://www.ilpago.eu/${path}" target="_blank" rel="noopener">${label} ↗</a>`;
const link=(href,label)=>`<a class="text-link" href="${href}">${label} <span aria-hidden="true">↗</span></a>`;
const request=(interest,label='Parliamone insieme')=>`<button class="text-link" data-booking="${interest}">${label} <span aria-hidden="true">↗</span></button>`;
const section=(id,kicker,title,body,extra='')=>({id,kicker,title,body,extra});
const details=(title,body)=>`<details><summary>${title}<span aria-hidden="true">+</span></summary><div>${body}</div></details>`;
export const pages=[
 {file:'il-pago.html',label:'Il Pago',eyebrow:'Una famiglia, una terra',title:'L’ospitalità<br>si <em>coltiva.</em>',description:'La famiglia Bianco, la masseria e l’azienda agricola Il Pago a Rotondella. Una storia di ospitalità, campagna e prodotti di stagione.',intro:'Ci sono luoghi che si conoscono un po’ alla volta. Con il profumo del giardino, una storia raccontata a tavola, un nome che diventa familiare.',image:'veranda',alt:'La veranda delle camere di Il Pago, aperta sul giardino',sections:[
 section('storia','01 / Le nostre radici','Una casa.<br><em>Molte generazioni.</em>',`<p>La famiglia Bianco si prende cura dell’azienda agricola dall’inizio del Novecento. L’agriturismo nasce da questo legame: accogliere significa condividere la vita della campagna, la sua cucina e il tempo che serve per apprezzarle.</p><p>La masseria si trova nel Metapontino, nel territorio di Rotondella. Il mare Jonio è a 4,5 km; Matera a 65 km. Qui si soggiorna in campagna, con la costa da raggiungere per una giornata al mare.</p>${source('')}`,{image:'exterior',alt:'La famiglia Bianco nel giardino di Il Pago'}),
 section('azienda','02 / L’azienda agricola','Il ritmo<br>delle <em>stagioni.</em>',`<p>Frutteti, ortaggi, olivi e grano legano il paesaggio alla tavola. L’azienda coltiva nella Piana del Metapontino e trasforma parte del raccolto nel proprio laboratorio: confetture, marmellate e passate conservano i sapori della stagione.</p><p>La produzione comprende il grano duro Senatore Cappelli. Per la disponibilità di sementi biologiche puoi contattare direttamente l’azienda.</p>${link('prodotti.html','Entra nella nostra dispensa')}${source('prodotti-tipici/','Agricoltura e trasformazione')}${source('prodotti-tipici/grano-cappelli/','Il grano Senatore Cappelli')}`,{image:'orchard',alt:'Ortaggi coltivati nei terreni dell’azienda agricola',caption:'Lascia vagare lo sguardo. La terra coltivata dell’azienda agricola Il Pago.'}),
 section('filosofia','03 / Il nostro modo di essere','Prendersi cura<br>di ciò che <em>conta.</em>',`<p>La filiera corta mette in relazione campo, laboratorio e cucina. La fattoria didattica apre questo percorso ai bambini: osservare, toccare e imparare diventano parte della visita.</p><div class="fact-list"><div><strong>Agricoltura biologica</strong><span>Certificazione n. L047/05, sezione A, riportata dall’azienda.</span></div><div><strong>Fattoria didattica riconosciuta</strong><span>Iscritta nell’elenco regionale della Basilicata.</span></div><div><strong>Bandiera Verde Agricoltura</strong><span>Tra i riconoscimenti pubblicati da Il Pago.</span></div><div><strong>Pera Signora</strong><span>Il Presidio Slow Food riguarda questa produzione tradizionale.</span></div></div>${source('prodotti-tipici/','Produzioni e riconoscimenti')}${link('esperienze.html#fattoria','Scopri la fattoria')}`)
 ],next:['ospitalita.html','Resta ancora un po’.']},
 {file:'ospitalita.html',label:'Ospitalità',eyebrow:'Il tuo tempo, senza fretta',title:'Il dolce<br><em>riposare.</em>',description:'Le otto camere di Il Pago: servizi, accessibilità, colazione, tariffe indicative e informazioni per organizzare il soggiorno a Rotondella.',intro:'Aprire la porta, trovare il verde. Otto camere con ingresso indipendente e il piacere semplice di sentirsi a casa.',image:'room-garden',alt:'Camera di Il Pago con letto matrimoniale e finestra sul verde',sections:[
 section('camere','01 / Le camere','Uno spazio<br>tutto <em>tuo.</em>',`<div class="fact-list"><div><strong>Comfort · fino a 4 ospiti</strong><span>25 m², matrimoniale e due letti singoli; bagno con doccia e bidet.</span></div><div><strong>Comfort accessibile · fino a 3 ospiti</strong><span>20 m², matrimoniale e singolo. Accesso senza gradini, porte ampie e bagno più spazioso.</span></div></div><p>Per scegliere la camera accessibile più adatta alle tue esigenze, descrivici ciò di cui hai bisogno prima di prenotare.</p>${request('Soggiorno','Scegliamo insieme la tua camera')}`,{gallery:true}),
 section('servizi','02 / Ogni giorno','La semplicità<br>del <em>comfort.</em>',`<ul class="service-list"><li>Bagno privato, doccia e asciugacapelli</li><li>Climatizzazione e riscaldamento autonomo</li><li>TV, Wi-Fi e mini frigo</li><li>Biancheria e riassetto quotidiano</li><li>Parcheggio privato</li><li>Giardino e solarium</li><li>Culla e seggiolone su richiesta</li><li>Spazi gioco per bambini</li></ul><p>Per chi viaggia in bicicletta sono disponibili deposito sicuro e ciclo-officina.</p>${link('esperienze.html#bicicletta','Viaggiare in bici')}${source('agriturismo/','Camere e servizi')}`,{image:'veranda',alt:'Poltrone e tavolini nella veranda delle camere'}),
 section('soggiorno','03 / Prima di partire','Le cose<br>da <em>sapere.</em>',`<div class="practical-grid"><div><span class="micro">Arrivo</span><strong>Dalle 16:00</strong></div><div><span class="micro">Partenza</span><strong>Entro le 10:00</strong></div><div><span class="micro">Colazione</span><strong>08:30–10:00</strong></div><div><span class="micro">Colazione extra</span><strong>€ 10 a persona</strong></div></div><p>Torte, pane, confetture e succhi accompagnano il risveglio. Culla su richiesta: € 10 al giorno. Sono disponibili proposte con pernottamento, colazione o mezza pensione.</p>${details('Tariffe delle camere · listino 2026',`<p>Tariffe a partire da, per camera e notte, solo pernottamento. La disponibilità e il preventivo si verificano al momento della prenotazione.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Listino camere 2026"><table><caption>Tariffe pubblicate da Il Pago</caption><thead><tr><th>Periodo</th><th>Singola</th><th>Doppia</th><th>Tripla</th><th>Quadrupla</th></tr></thead><tbody><tr><th>Gen–Apr / Ott–Dic</th><td>€ 35</td><td>€ 55</td><td>€ 80</td><td>€ 100</td></tr><tr><th>Mag–Giu / Set</th><td>€ 50</td><td>€ 80</td><td>€ 110</td><td>€ 135</td></tr><tr><th>Lug–Ago / festività</th><td>€ 70</td><td>€ 110</td><td>€ 155</td><td>€ 200</td></tr></tbody></table></div>${source('agriturismo/','Listino e condizioni aggiornate')}`)}${details('Conferma e cancellazioni',`<p>La conferma prevede un acconto del 30% entro tre giorni lavorativi. Il saldo è previsto il giorno prima della partenza.</p><p>Le penali aumentano avvicinandosi all’arrivo: 10% fino a 20 giorni prima, 30% tra 19 e 10, 50% tra 9 e 5, 100% da 4 giorni. La partenza anticipata non prevede rimborso. Prima di confermare, consulta le condizioni complete e chiedi il preventivo per le tue date.</p>${source('agriturismo/','Condizioni complete del soggiorno')}`)}${details('Esigenze particolari',`<p>Per accessibilità, alimentazione, arrivi fuori orario o soggiorni con animali, contattaci prima di prenotare: ti daremo indicazioni specifiche per la tua visita.</p>${request('Soggiorno','Raccontaci le tue esigenze')}`)}`),
 section('proposte','04 / Un motivo per partire','Scegli il tuo<br><em>ritmo.</em>',`<p>Una vacanza in famiglia, una sosta in bicicletta, un fine settimana tra sapori e territorio. Esplora le proposte e chiedici quali sono disponibili nelle tue date.</p>${link('soggiorni.html','Proposte di soggiorno')}${request('Soggiorno','Richiedi disponibilità')}`)
 ],next:['ristorante.html','Ci ritroviamo a tavola.']},
 {file:'ristorante.html',label:'Ristorante',eyebrow:'La campagna, a tavola',title:'Il sapore delle<br>nostre <em>radici.</em>',description:'Il ristorante di Il Pago a Rotondella: cucina lucana, ingredienti aziendali e del territorio, tavoli in giardino e ricette di famiglia.',intro:'La pasta si prepara a mano. Gli ingredienti seguono il raccolto. E la tavola è il posto dove le storie si incontrano.',image:'restaurant-table',alt:'Una tavola apparecchiata nella sala del ristorante Il Pago',sections:[
 section('cucina','01 / La cucina','Il buono<br>della <em>tradizione.</em>',`<p>La cucina del Pago nasce dai gesti di casa: la pasta lavorata a mano, le verdure dell’orto, il calore della brace. La stagione suggerisce cosa portare in tavola.</p><p>Antipasti, frizzuli con mollica, arrosti di agnello e salsiccia, costine di maiale e frutta sono alcune delle proposte della cucina lucana. Il menù del giorno si concorda con il ristorante.</p>${source('ristorante/','La cucina e il menù tipico')}`,{image:'grill',alt:'Carne cotta sulla brace nella cucina del Pago',caption:'Il calore della brace, i sapori della cucina di casa.'}),
 section('tavola','02 / Il ristorante','C’è posto<br>anche per <em>te.</em>',`<p>Una tavolata apparecchiata, i bicchieri pronti, il piacere di stare insieme. In autunno e in inverno ci si ritrova nella sala interna, vicino al camino.</p><p>Con la bella stagione si mangia anche all’aperto. Grigliate, pasta fresca, formaggi e verdure dell’orto accompagnano le serate, insieme ai vini lucani, tra cui l’Aglianico del Vulture.</p>${request('Ristorante','Ci vediamo a tavola')}`,{image:'table-glasses',alt:'La lunga tavolata del ristorante Il Pago, apparecchiata con bicchieri e tovaglia bianca',caption:'La sala del ristorante, pronta per un pranzo da condividere.'}),
 section('ingredienti','03 / Dal campo','Una cucina<br>che sa da dove <em>viene.</em>',`<p>Semola Senatore Cappelli, olio extravergine, uova, passate, frutta, ortaggi, miele e confetture collegano la cucina all’azienda.</p><p>Accanto ai prodotti di casa trovano posto i sapori lucani: Pera Signora, peperoni di Senise, Canestrato di Moliterno, fagioli di Sarconi e vini del territorio.</p>${link('prodotti.html','I prodotti da portare a casa')}${source('prodotti-tipici/','Produzioni aziendali e filiera corta')}`,{stories:[
  {image:'orchard',alt:'Ortaggi nell’azienda agricola Il Pago',title:'La stagione, a km zero.',text:'Frutta e ortaggi crescono nei terreni dell’azienda, con agricoltura biologica. Il raccolto maturo arriva in cucina e nel laboratorio di trasformazione.'},
  {image:'preserves',alt:'Confetture e marmellate prodotte da Il Pago',title:'Il raccolto, da conservare.',text:'Confetture, marmellate e passate custodiscono i sapori della campagna. La frutta viene lavorata con metodi tradizionali, senza conservanti e pectina.'}
 ]}),
 section('ricette','04 / Il quaderno di casa','Le mani ricordano.<br>Il gusto <em>rimane.</em>',`<p>Quattro ricette del Pago, con i loro nomi e i loro sapori. Scegli una ricetta per scoprire ingredienti e preparazione.</p>`,{stories:recipes.map(r=>({...r,text:r.description,href:recipeUrl(r.id),link:'Scopri la ricetta'})),layout:'recipes'}),
 section('prenotare','05 / Ti teniamo un posto','A tavola,<br><em>insieme.</em>',`<p>Il ristorante è aperto tutti i giorni su prenotazione. Per il pranzo della domenica è preferibile contattarci con maggiore anticipo.</p><p>Per una festa o un’occasione importante puoi concordare un pranzo o una cena: raccontaci il numero di persone e la data. Comunica eventuali allergie o esigenze alimentari quando prenoti.</p><p>Per gli ospiti, è previsto anche un menù completo a € 30: antipasto, primo oppure secondo con contorno, frutta, acqua e vino della casa. Chiedi conferma della proposta disponibile.</p>${request('Ristorante','Prenota il tuo tavolo')}${source('ristorante/','Apertura e occasioni a tavola')}${source('agriturismo/','Trattamenti per gli ospiti')}`)
 ],next:['prodotti.html','Un po’ del Pago, con te.']},
 {file:'esperienze.html',label:'Esperienze',eyebrow:'Piccole cose, grandi ricordi',title:'Segui la tua<br><em>natura.</em>',description:'Fattoria didattica, tre laboratori per scuole e famiglie, passeggiate a cavallo, trail running, cicloturismo e sapori a Il Pago.',intro:'Una piantina da portare a casa. La prima passeggiata a cavallo. Una strada da percorrere piano. Scegli cosa ti va di vivere.',image:'farm',alt:'Un bambino incontra gli asinelli nella fattoria Il Pago',sections:[
 section('fattoria','01 / La scuola all’aperto','La campagna<br><em>insegna.</em>',`<p>La fattoria didattica, riconosciuta dalla Regione Basilicata, accoglie scuole, famiglie e gruppi. La visita dura circa tre ore e comprende una merenda con miele e confetture aziendali.</p><div class="editorial-details">${details('Dal seme al frutto',`<p>Dopo aver scoperto il ciclo delle piante, i bambini sistemano un germoglio in un piccolo contenitore. La piantina torna a casa con loro, per continuare a osservarla e curarla.</p>`)}${details('Dal fiore al miele',`<p>Si conoscono i ruoli delle api, l’organizzazione dell’alveare, la produzione di cera e miele e il percorso della raccolta fino al vasetto.</p>`)}${details('Dal frutto al vasetto',`<p>Dalla fioritura alla raccolta, fino alla visita del laboratorio: si scoprono lavorazione, macchinari e confezionamento delle confetture.</p>`)}</div><p>Per organizzare una visita, indica data, numero dei partecipanti ed età dei bambini.</p>${request('Fattoria didattica','Organizza una visita')}${source('fattoria-didattica/','Percorsi didattici completi')}`,{image:'seedlings',alt:'Bambini e un’adulta piantano i germogli nell’orto del Pago'}),
 section('cavalli','02 / Le prime scoperte','Un incontro<br><em>speciale.</em>',`<p>Con Scuderia 34, Il Pago propone nei weekend passeggiate guidate dentro l’azienda, pensate anche per adulti e bambini alle prime esperienze. La passeggiata dura circa 15 minuti a persona; sono consigliati pantaloni comodi e scarpe chiuse. Prenota per concordare disponibilità e partecipazione.</p><p>Per escursioni più ampie in campagna e sulla spiaggia, i centri ippici di Policoro e Nova Siri propongono corsi e passeggiate organizzate.</p>${request('Passeggiata a cavallo','Chiedi una passeggiata')}${source('offerte/passeggiata-cavalli/','Passeggiate al Pago con Scuderia 34')}${source('territorio/maneggio/','Maneggi ed escursioni nei dintorni')}`,{image:'horses',alt:'Passeggiata a cavallo lungo un percorso nella campagna, foto ufficiale Il Pago'}),
 section('trail','03 / All’aria aperta','Un passo<br>alla <em>volta.</em>',`<p>Un anello di circa 1.500 metri segue il perimetro dell’azienda, prevalentemente su terra battuta. Il dislivello è di 15 metri: un percorso per correre o concedersi una passeggiata tra i suoni della campagna.</p><div class="practical-grid"><div><span class="micro">Percorso</span><strong>1,5 km</strong></div><div><span class="micro">Dislivello</span><strong>15 m</strong></div></div>${source('offerte/trail-running/','Consulta la mappa del percorso')}`),
 section('bicicletta','04 / In sella','La strada<br>ti <em>aspetta.</em>',`<p>Il Pago dispone di una Bike Area con deposito sicuro e ciclo-officina interna, a disposizione di chi soggiorna e dei ciclisti che si fermano al ristorante.</p><p>Le escursioni guidate esplorano Rotondella, Nova Siri, Valsinni e l’area archeologica di Policoro. Puoi chiedere informazioni sui percorsi della Ciclovia Basilicata Coast to Coast e organizzare la tua uscita.</p>${request('Cicloturismo','Organizza la tua sosta in bici')}${source('territorio/bike/','Servizi e itinerari in bicicletta')}`),
 section('sapori','05 / Esperienze di gusto','Il piacere<br>di <em>condividere.</em>',`<p>Una visita ai vigneti e alla cantina di Masseria Battifarano, con degustazione di vini del territorio, dà un altro sapore al soggiorno. Il corso “Sapori e Mani in Pasta” appartiene invece al programma del 16–18 gennaio 2026: puoi chiedere se sono previste nuove date.</p>${link('soggiorni.html#sapori','Scopri le proposte e le date')}${link(recipeIndex,'Prova le ricette a casa')}`)
 ],next:['territorio.html','Oltre il nostro giardino.']}
];
export {source,link,request,section,details};
