// Names and photographs follow the restaurant's official recipe archive.
export const recipeUrl = id => `ricetta-${id}.html`;
export const recipeIndex = 'ristorante.html#ricette';
export const recipes = [
 {id:'pastizz',title:"U' Pastizz R'tunnar",image:'recipe-pastizz',alt:"U' Pastizz R'tunnar, i rustici a mezzaluna preparati al Pago",description:'Il rustico di Rotondella: una sfoglia di grano duro racchiude carne di maiale, uova, formaggio e prezzemolo.',path:'pastizz/',method:'Lascia riposare l’impasto per mezz’ora, poi stendilo in dischi sottili. Distribuisci il ripieno su metà di ciascun disco, richiudi a mezzaluna e sigilla i bordi. Fora la superficie e spennella con tuorlo: la ricetta indica circa venti minuti in forno a 200 °C.'},
 {id:'pan-brioche',title:'Pan Brioche',image:'recipe-brioche',alt:'Una fetta di Pan Brioche farcito, dalla ricetta ufficiale Il Pago',description:'Una treccia salata da condividere. Nella ricetta di casa, l’impasto al latte accoglie mozzarella e speck.',path:'panbrioche/',method:'Prepara l’impasto con farina, latte, olio, sale, zucchero, lievito e uovo. Stendilo in strisce, aggiungi mozzarella e speck, richiudi e intreccia i filoni. Dopo circa un’ora di lievitazione, cuoci in forno a 200 °C per circa trenta minuti. Lascia intiepidire prima di servire.'},
 {id:'torta-della-nonna',title:'Torta della Nonna',image:'recipe-torta-2',alt:'La Torta della Nonna del Pago, farcita e spolverata con zucchero a velo',description:'Pan di Spagna al limone con farina Senatore Cappelli. Da farcire con crema, marmellata o confettura.',path:'torta/',method:'Monta uova e zucchero, poi incorpora farina, fecola, olio, succo e scorza di limone e lievito. La ricetta indica trenta minuti a 150 °C. Una volta freddo, dividi il Pan di Spagna, farciscilo e completa con zucchero a velo. Nel quaderno trovi anche la preparazione della crema al limone.'},
 {id:'frizzuli',title:"Frizzul ca Middich'",image:'recipe-frizzul',alt:"Frizzul ca Middich', pasta al pomodoro e mollica nella ricetta del Pago",description:'Pasta lavorata al ferro, sugo di pomodoro e mollica tostata con peperone in polvere di Senise.',path:'sugo/',method:'Lavora semola Senatore Cappelli, uova, acqua e sale, poi lascia riposare mezz’ora. Forma i frizzuli con il ferro. Prepara il sugo con pomodorini, aglio, cipolla e basilico; a parte tosta la mollica con olio e peperone in polvere. Cuoci la pasta e unisci il condimento e la mollica croccante.'}
];
export const recipeIngredients = {
 pastizz:'Per 8–10 pastizz. Impasto: 1 kg di farina di grano duro, 30 g di sale, 150 g di olio extravergine e 450 g di acqua. Ripieno: 1 kg di carne di maiale, 2 uova, 100 g di olio, prezzemolo, pepe, sale e formaggio quanto basta.',
 'pan-brioche':'Per 2 Pan Brioche. Impasto: 500 g di farina bianca, 250 ml di latte, 60 g di olio extravergine, 20 g di sale, 10 g di zucchero, un cubetto di lievito e un uovo. Farcitura: 500 g di mozzarella e 500 g di speck. La ricetta indica anche formaggi e salumi alternativi.',
 'torta-della-nonna':'Per una torta. Pan di Spagna: 6 uova, 400 g di zucchero, 400 g di farina Senatore Cappelli, 2 limoni, 150 g di olio extravergine, 15 g di fecola e 16 g di lievito per dolci. Crema: 1 litro di latte intero, 6 tuorli, 200 g di zucchero, 100 g di farina Senatore Cappelli e scorza di un limone.',
 frizzuli:'Per 4 persone. Pasta: 400 g di semola Senatore Cappelli, 2 uova, 110 g di acqua e sale. Sugo: 500 g di passata con pomodorini, uno spicchio d’aglio, 20 g di cipolla, 50 g di olio, sale e basilico. Mollica: 50 g di pane raffermo, 15 g di peperone in polvere di Senise e un filo d’olio.'
};
