import {source,link,request,section} from './pages.mjs';
export const territoryPage = {
 file:'territorio.html',label:'Territorio',eyebrow:'Rotondella · Metapontino · Basilicata',title:'Ogni strada,<br>una <em>scoperta.</em>',description:'Rotondella, Matera, Craco, costa ionica, Metaponto, Policoro e Oasi WWF: un viaggio fotografico nei dintorni del Pago.',intro:'La campagna è il punto di partenza. Poco più in là, il mare. Poi i borghi, le pietre antiche e i paesaggi da attraversare senza fretta.',image:'matera',alt:'Il panorama dei Sassi di Matera, dalla galleria ufficiale Il Pago',sections:[
  section('rotondella','01 / Il nostro borgo','Rotondella.<br>Il balcone sullo <em>Ionio.</em>',`<p>Il borgo si raccoglie su una collina a circa 500 metri di quota. Dai belvederi lo sguardo attraversa il Metapontino; nel centro storico si cammina tra vicoli, palazzi e le Lamie di Bitonte.</p><p>La Chiesa di Santa Maria delle Grazie, il complesso di Sant’Antonio e la Torre del Carcere raccontano il paese. Anche il pastizz, le feste e le sagre ne custodiscono l’identità: chiedici cosa è in programma durante il tuo soggiorno.</p>${source('territorio/rotondella/','Conosci Rotondella')}`,{image:'rotondella',alt:'Rotondella vista dall’alto, raccolta intorno alla collina',caption:'Rotondella, il borgo da cui comincia il viaggio.'}),
  section('mare','02 / A 4,5 km','La costa<br><em>ionica.</em>',`<p>Lunghe spiagge sabbiose, acqua aperta e vegetazione mediterranea. Dal Pago puoi raggiungere il mare e tornare alla quiete della campagna a fine giornata.</p><p>Scegli una spiaggia libera oppure chiedici informazioni sugli stabilimenti convenzionati. Servizio spiaggia, disponibilità e costi si concordano prima della visita.</p>${source('territorio/mare/','Scopri la costa ionica')}${source('offerte/estate/','Spiagge e convenzioni')}${request('Soggiorno','Organizza le tue giornate al mare')}`,{image:'ionio',alt:'La spiaggia ionica lucana e la vegetazione mediterranea',caption:'Il piacere di una giornata sulla costa ionica.'}),
  section('vicino','03 / Il Metapontino','Tra natura<br>e <em>Magna Grecia.</em>',`<p>Un museo, le colonne di un tempio, un bosco che arriva al mare. Tre modi diversi di incontrare il paesaggio intorno a noi.</p>`,{stories:[
   {id:'policoro',image:'policoro',alt:'Vasi antichi esposti nel Museo Archeologico Nazionale della Siritide',title:'Policoro e la Siritide',text:'Il parco archeologico dell’antica Heraclea e il Museo Archeologico Nazionale della Siritide raccontano la storia del territorio. Nelle collezioni si incontrano reperti di Siris, di Heraclea e delle comunità delle valli dell’Agri e del Sinni.',source:'territorio/policoro/'},
   {id:'metaponto',image:'metaponto',alt:'Le colonne delle Tavole Palatine a Metaponto',title:'Metaponto e le Tavole Palatine',text:'Le colonne del tempio dedicato a Hera restano un segno della Magna Grecia nel paesaggio lucano. L’area archeologica e il Museo Archeologico Nazionale completano la visita di Metaponto.',source:'territorio/metaponto/'},
   {id:'oasi-wwf',image:'wwf',alt:'Liberazione di una tartaruga marina sulla spiaggia con l’Oasi WWF Policoro Herakleia',title:'Oasi WWF Policoro Herakleia',text:'Nella Riserva Bosco Pantano, zone umide e bosco ospitano uccelli migratori e fauna mediterranea. Il centro di recupero cura anche le tartarughe marine: un incontro con la natura e con chi se ne prende cura.',source:'territorio/wwf/'}
  ]}),
  section('matera','04 / I paesaggi di pietra','La memoria<br>dei <em>luoghi.</em>',`<p>Dedica una giornata ai Sassi, oppure parti alla scoperta di un borgo sospeso nel paesaggio. Da qui la Basilicata mostra altri volti.</p>${request('Territorio e visite','Chiedi informazioni sulle visite')}`,{stories:[
   {image:'matera-wide',alt:'Il centro storico di Matera e il panorama dei Sassi',title:'Matera, a 65 km dal Pago',text:'Case-grotta, vicoli e chiese rupestri compongono una città da attraversare a piedi. Puoi chiedere visite personalizzate con guide autorizzate, anche per singoli e piccoli gruppi, tra i Sassi, la Murgia e la Gravina.',source:'territorio/matera/'},
   {id:'craco',image:'craco',alt:'La torre e le case del borgo abbandonato di Craco',title:'Craco, il paese fantasma',text:'La torre e le case disabitate emergono dalla collina. Il borgo, abbandonato dopo le frane, offre uno dei paesaggi più riconoscibili della regione. Prima di partire, verifica i percorsi di visita autorizzati e l’accessibilità.',source:'territorio/craco/'}
  ]}),
  section('basilicata','05 / All’aria aperta','Lasciati portare<br><em>lontano.</em>',`<p>Il Pollino, le Dolomiti Lucane e gli itinerari dei castelli di Lagopesole, Melfi e Venosa invitano ad allargare il viaggio. Pianifica le mete regionali dedicando il tempo necessario agli spostamenti.</p>${source('territorio/','Gli itinerari in Basilicata')}`,{stories:[
   {image:'volo-angelo',alt:'Il Volo dell’Angelo sopra il paesaggio delle Dolomiti Lucane',title:'Il Volo dell’Angelo',text:'Tra Castelmezzano e Pietrapertosa, un cavo sospeso attraversa la valle delle Dolomiti Lucane. Per partecipare, consulta disponibilità, requisiti e prenotazioni dell’organizzatore.',source:'territorio/volo-angelo/'},
   {image:'horses',alt:'Passeggiata a cavallo nella campagna lucana',title:'In sella, nella natura',text:'I maneggi di Policoro e Nova Siri organizzano passeggiate in campagna e sulla spiaggia. Al Pago, con Scuderia 34, puoi invece chiedere le passeggiate guidate in azienda, adatte anche alle prime esperienze.',href:'esperienze.html#cavalli',link:'Passeggiate e informazioni'}
  ]}),
  section('partire','06 / Prima di partire','Scegli la tua<br><em>giornata.</em>',`<p>Per musei, oasi, visite guidate e attività, verifica aperture e disponibilità nelle date del soggiorno. Saremo felici di aiutarti a scegliere il percorso.</p>${request('Territorio e visite','Organizziamo la tua visita')}${link('esperienze.html#bicicletta','Esplora anche in bicicletta')}`)
 ],next:['ospitalita.html','Il tuo posto da cui partire.']
};
