import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {pages} from '../content/pages.mjs';
import {discoverPages} from '../content/discover.mjs';
import {gardenCanopy, coastalScene} from '../content/scenes.mjs';
import {showcaseScene} from '../content/showcase.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFile(path.join(root,p),'utf8');
const runtimeFiles=['style.css','motion.css','refinement.css','scenography.css','showcase.css','script.js','motion.js','editorial.js','atmosphere.js','showcase.js'];
const versions=new Map(await Promise.all(runtimeFiles.map(async file=>[file,createHash('sha256').update(await read(file)).digest('hex').slice(0,10)])));
// Revalidate changed code/styles for returning visitors after a Pages deployment.
const write=(p,s)=>fs.writeFile(path.join(root,p),s.replace(/(href|src)="([^"?]+\.(?:css|js))"/g,(match,attribute,file)=>versions.has(file)?`${attribute}="${file}?v=${versions.get(file)}"`:match));
const original=await read('content/home-source.html');
const manifest=JSON.parse(await read('assets/images.json'));
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;');
const arrow='<svg aria-hidden="true"><use href="#arrow"/></svg>';
const heroSizes=name=>{const m=manifest[name],ratio=m.width/m.height;return `(max-width: 760px) max(90vw, ${Math.round(ratio*55)}svh), max(52vw, ${Math.round(ratio*64)}svh)`;};
// Object-fit crops need enough source pixels for the image's height, especially on portrait iPads.
const storySizes='(max-width: 760px) max(110vw, 68svh), max(60vw, 125svh)';
const picture=(name,alt,cls='',eager=false,sizes='(max-width: 760px) 100vw, 60vw')=>{
 const m=manifest[name],v=m.variants;return `<img class="${cls}" src="${v.at(-1).src}" srcset="${v.map(x=>`${x.src} ${x.width}w`).join(', ')}" sizes="${sizes}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
};
const preload=(name,sizes="100vw")=>{const v=manifest[name].variants;return `<link rel="preload" as="image" href="${v.at(-1).src}" imagesrcset="${v.map(x=>`${x.src} ${x.width}w`).join(', ')}" imagesizes="${sizes}" fetchpriority="high">`};
const groups=[
 ['Il Pago','il-pago.html',[['Storia e famiglia','il-pago.html#storia'],['Azienda agricola','il-pago.html#azienda']]],
 ['Ospitalità','ospitalita.html',[['Camere e servizi','ospitalita.html#camere'],['Soggiorno e tariffe','ospitalita.html#soggiorno'],['Proposte','soggiorni.html']]],
 ['La tavola','ristorante.html',[['Il ristorante','ristorante.html'],['Prodotti','prodotti.html'],['Ricette','ricette.html']]],
 ['Esperienze','esperienze.html',[['Fattoria didattica','esperienze.html#fattoria'],['Cavalli e natura','esperienze.html#cavalli'],['In bicicletta','esperienze.html#bicicletta']]],
 ['Territorio','territorio.html',[['Rotondella','territorio.html#rotondella'],['Lo Jonio','territorio.html#mare'],['Borghi e itinerari','territorio.html#vicino']]]
];
const menu=`<dialog data-lenis-prevent class="menu-dialog side-dialog" id="menu-dialog" aria-labelledby="menu-title"><div class="dialog-top"><span class="micro" id="menu-title">Il Pago · Esplora</span><button class="close-button" data-close="menu-dialog" aria-label="Chiudi il menu" autofocus>Chiudi <svg aria-hidden="true"><use href="#close"/></svg></button></div><a class="menu-home micro" href="index.html">La tua casa fuori casa ↗</a><nav class="drawer-navigation" aria-label="Navigazione principale">${groups.map(([label,href,sub],i)=>`<div class="menu-group" style="--menu-i:${i}"><a class="menu-primary" href="${href}"><span class="micro">0${i+1}</span>${label}<span class="menu-arrow" aria-hidden="true">↗</span></a><div class="menu-sub">${sub.map(([label,href])=>`<a href="${href}">${label}</a>`).join('')}</div></div>`).join('')}<a class="menu-contact" href="contatti.html" data-contact><span class="micro">06</span>Contatti <span aria-hidden="true">↗</span></a></nav><div class="menu-bottom"><p class="script">Ti aspettiamo.</p><a class="micro" href="tel:+393383222295">+39 338 322 2295 ↗</a></div></dialog>`;
const contactBody=`<span class="micro">Un messaggio, una telefonata</span><h2 class="display" id="contact-title">Facciamo<br><span class="script">come a casa.</span></h2><p>Per un soggiorno, un tavolo o una giornata da trascorrere insieme.</p><div class="contact-panel-grid"><div><span class="micro">Parliamone</span><a class="contact-phone" href="tel:+393383222295">+39 338 322 2295</a><a href="tel:+393884712023">+39 388 471 2023</a><a href="mailto:info@ilpago.eu">info@ilpago.eu</a></div><div><span class="micro">Vieni a trovarci</span><address>Via Piano del Forno, 7<br>75026 Rotondella (MT)<br>Basilicata, Italia</address><a class="text-link" href="https://www.google.com/maps/dir/?api=1&amp;destination=Agriturismo+Il+Pago+Via+Piano+del+Forno+7+Rotondella" target="_blank" rel="noopener">Come arrivare ↗</a></div><div><span class="micro">Ufficio prenotazioni</span><p>09:00–14:00 · 16:00–21:00</p></div></div><div class="contact-actions"><button class="text-link" data-booking="Soggiorno">Prepara una richiesta WhatsApp ${arrow}</button><a class="text-link" href="https://hospitality-guest.teamsystem.cloud/booking-engine/azienda-agrituristica-il-pago" target="_blank" rel="noopener">Disponibilità e prenotazione online ↗</a></div><div class="contact-socials"><a href="https://www.facebook.com/agriturismoilpago/" target="_blank" rel="noopener">Facebook ↗</a><a href="https://www.instagram.com/agriturismoilpago/" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.tripadvisor.it/Hotel_Review-g2292011-d2323799-Reviews-Azienda_Agrituristica_Il_Pago-Rotondella_Province_of_Matera_Basilicata.html" target="_blank" rel="noopener">Le vostre recensioni ↗</a></div>`;
const contacts=`<dialog data-lenis-prevent class="contact-dialog side-dialog" id="contact-dialog" aria-labelledby="contact-title"><div class="dialog-top"><span class="micro">Il Pago · Contatti</span><button class="close-button" data-close="contact-dialog" aria-label="Chiudi i contatti" autofocus>Chiudi <svg aria-hidden="true"><use href="#close"/></svg></button></div><div class="contact-panel">${contactBody}</div></dialog>`;
let booking=original.match(/<dialog data-lenis-prevent class="booking-dialog"[\s\S]*?<\/dialog>/)[0];
booking=booking.replace('<option value="Prodotti tipici">Conoscere i prodotti</option>','<option value="Prodotti tipici">Conoscere i prodotti</option><option value="Passeggiata a cavallo">Passeggiare a cavallo</option><option value="Cicloturismo">Organizzare una sosta in bici</option><option value="Esperienze di gusto">Corsi e degustazioni</option><option value="Territorio e visite">Organizzare una visita guidata</option>');
booking=booking.replace('name="messaggio"','name="messaggio"').replace('<p class="form-note">','<p class="form-note"><a href="privacy.html">Informazioni sul trattamento dei dati</a>. ');
const dialogs=menu+contacts+booking;
const svg=original.match(/<svg class="svg-library"[\s\S]*?<\/svg>/)[0];
const header=original.match(/<header class="site-header"[\s\S]*?<\/header>/)[0].replace('href="#contatti"','href="contatti.html" data-contact aria-haspopup="dialog" aria-controls="contact-dialog"');
const footer=original.match(/<footer class="site-footer[\s\S]*?<\/footer>/)[0].replace('<div class="footer-bottom',`<nav class="footer-links" aria-label="Esplora Il Pago">${groups.map(([label,href])=>`<a href="${href}">${label}</a>`).join('')}<a href="contatti.html" data-contact>Contatti</a><a href="privacy.html">Privacy</a></nav><div class="footer-bottom`);
const noScript='<noscript><nav class="no-script-nav" aria-label="Navigazione senza JavaScript">'+groups.map(([label,href])=>`<a href="${href}">${label}</a>`).join('')+'<a href="contatti.html">Contatti</a></nav></noscript>';
const common=(inner=false)=>header.replaceAll('href="#home"',inner?'href="index.html"':'href="#home"');
const pageFooter=(inner=false)=>footer.replaceAll('href="#home"',inner?'href="#main"':'href="#home"');
const head=(title,desc,photo,home=false)=>`<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#223c2d"><title>${title} · Il Pago, Rotondella</title><meta name="description" content="${esc(desc)}"><meta property="og:title" content="${esc(title)} · Il Pago"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><link rel="icon" href="assets/flower.svg" type="image/svg+xml"><link rel="preload" href="assets/bodoni.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/pinyon.ttf" as="font" type="font/ttf" crossorigin>${photo?preload(photo,home?'(max-width: 760px) 180vw, 100vw':heroSizes(photo)):''}<link rel="stylesheet" href="style.css"><link rel="stylesheet" href="motion.css"><link rel="stylesheet" href="refinement.css">${home?'<link rel="stylesheet" href="scenography.css"><link rel="stylesheet" href="showcase.css">':''}<script src="assets/vendor/gsap.min.js" defer></script><script src="assets/vendor/ScrollTrigger.min.js" defer></script>${home?'<script src="assets/vendor/lenis.min.js" defer></script>':''}<script src="script.js" defer></script><script src="${home?'motion':'editorial'}.js" defer></script>${home?'<script src="atmosphere.js" defer></script><script src="showcase.js" defer></script>':''}</head>`;
const roomGallery=`<div class="detail-room-gallery"><figure>${picture('room-2','Camera con letto in ferro battuto e soffitto in legno')}<figcaption>Una delle camere di Il Pago.</figcaption></figure><figure>${picture('room-3','Bagno di una delle camere di Il Pago, con lavabo e doccia')}<figcaption>Il bagno delle camere di nuova realizzazione.</figcaption></figure></div>`;
const renderSection=s=>`<section class="detail-section ${s.extra?.image?'with-photo':''}" id="${s.id}" aria-labelledby="heading-${s.id}"><div class="detail-section-heading"><span class="micro">${s.kicker}</span><h2 id="heading-${s.id}">${s.title}</h2></div><div class="detail-section-body">${s.body}</div>${s.extra?.image?`<figure class="detail-figure photo-${s.extra.image}" style="--photo-native:${manifest[s.extra.image].width}px">${picture(s.extra.image,s.extra.alt,'',false,'(max-width: 760px) 110vw, (min-width: 2000px) 1600px, 90vw')}<figcaption>${s.extra.caption||s.extra.alt}</figcaption></figure>`:s.extra?.gallery?roomGallery:''}</section>`;
for(const p of [...pages,...discoverPages]){
 const markup=`${head(p.label,p.description,p.image)}<body class="editorial-page"><a class="skip-link" href="#main">Vai al contenuto</a>${svg}${common(true)}${noScript}<main id="main" tabindex="-1"><section class="detail-hero"><div class="detail-hero-copy"><a class="micro breadcrumb" href="index.html">Il Pago / ${p.label}</a><span class="micro detail-eyebrow">${p.eyebrow}</span><h1>${p.title}</h1><p>${p.intro}</p><a class="text-link" href="#${p.sections[0].id}">Scopri ${arrow}</a></div><figure>${picture(p.image,p.alt,'',true,heroSizes(p.image))}</figure><span class="detail-hero-note micro">La tua casa fuori casa · Rotondella</span></section><nav class="chapter-nav" aria-label="In questa pagina">${p.sections.map(s=>`<a href="#${s.id}">${s.kicker.split(' / ')[1]}</a>`).join('')}</nav><div class="detail-content section-pad">${p.sections.map(renderSection).join('')}</div><a class="next-chapter section-pad" href="${p.next[0]}"><span class="micro">Il viaggio continua</span><span>${p.next[1]}</span>${arrow}</a></main>${pageFooter(true)}${dialogs}</body></html>`;
 await write(p.file,markup);
}
let main=original.match(/<main id="main">[\s\S]*?<\/main>/)[0];
// Successful hero composition remains intact; only responsive asset variants change.
main=main.replace(/<img class="hero-day"[^>]+>/,picture('courtyard','','hero-day',true,'(max-width: 760px) 180vw, 100vw')).replace(/<img class="hero-night"[^>]+>/,picture('courtyard-night','','hero-night',false,'(max-width: 760px) 180vw, 100vw'));
main=main.replace(/<section class="contact section-pad"[\s\S]*?<\/section>/,'').replace(/<section class="farm-section section-pad"[\s\S]*?<\/section>/,'');
main=main.replace('href="#storia"','href="il-pago.html"');
const passage=`<section class="passage" id="la-porta" aria-labelledby="passage-title" data-surface="paper"><div class="passage-stage"><div class="passage-label micro"><span>Il giardino, quando arriva la sera.</span><span>Un altro tempo · Il Pago</span></div><div class="passage-frame">${picture('garden-evening','Il giardino autentico di Il Pago illuminato per la sera','','', '(max-aspect-ratio: 4/3) 134svh, 100vw')}<div class="passage-shade"></div></div><div class="passage-invitation"><span class="micro">Entra. Ti aspettavamo.</span><p>Benvenuti<span class="script">al Pago.</span></p></div><h2 class="display passage-title" id="passage-title">Qui, il tempo<br>si fa <span class="script">nostro.</span></h2><p class="passage-foot micro">Un piccolo mondo, tutto da vivere.</p></div></section>`;
main=main.replace(/<section class="passage"[\s\S]*?<\/section>/,passage);
main=main.replace(/<img src="assets\/courtyard.jpg"[^>]+>/,picture('veranda','La veranda delle camere affacciata sul giardino','','','(max-width: 760px) 105vw, max(52vw, 110svh)'));
main=main.replace(/<img src="assets\/exterior.jpg"[^>]+>/,picture('exterior','La famiglia Bianco nel giardino del Pago','','','(max-width: 760px) 45vw, 370px'));
main=main.replace('<figure class="family-photo">','<a class="text-link story-more" href="il-pago.html">La nostra storia '+arrow+'</a><figure class="family-photo">');
const galleryData=[{"asset":"room-garden","alt":"Camera di Il Pago con letto matrimoniale e finestra sul verde","caption":"Il tuo rifugio in campagna"},{"asset":"room-2","alt":"Camera di Il Pago con letti in ferro battuto e soffitto in legno","caption":"La semplicità del riposo"},{"asset":"room-1","alt":"Un altro punto di vista della camera con soffitto in legno","caption":"Un posto tutto tuo"}].map(({asset,alt,caption})=>{const m=manifest[asset],v=m.variants;return {src:v.at(-1).src,srcset:v.map(x=>`${x.src} ${x.width}w`).join(', '),width:m.width,height:m.height,alt,caption};});
main=main.replace('<div class="room-gallery reveal"','<div class="room-gallery reveal" data-room-gallery="'+esc(JSON.stringify(galleryData))+'"');
main=main.replace(/<img data-room-image[^>]+>/,picture('room-garden','Camera di Il Pago con finestra sul verde','','','(max-width: 760px) max(110vw, 70svh), max(65vw, 85svh)').replace('<img ','<img data-room-image ')).replace('data-room-caption>Il giardino sulla soglia','data-room-caption>Il tuo rifugio in campagna');
main=main.replace('Richiedi disponibilità <svg>','Richiedi disponibilità <svg>');
main=main.replace('<a class="micro booking-online"','<a class="text-link rooms-more" href="#scopri-il-pago" data-showcase="ospitalita">Camere, servizi e soggiorno '+arrow+'</a><a class="micro booking-online"');
main=main.replace(/<img src="assets\/pasta.jpg"[^>]+>/,picture('restaurant-table','Tavola apparecchiata nella sala del ristorante Il Pago','','','(max-width: 760px) max(100vw, 98svh), max(50vw, 110svh)'));
main=main.replace('<div class="table-specialty">','<a class="text-link" href="ristorante.html">La cucina, i prodotti, le ricette '+arrow+'</a><div class="table-specialty">');
main=main.replace('href="#fattoria"','href="#scopri-il-pago" data-showcase="fattoria"').replace(/<img src="assets\/farm.jpg"[^>]+>/,picture('farm','Un bambino incontra gli asinelli nella fattoria Il Pago','','',storySizes));
main=main.replace('<button class="card-button" data-booking="Prodotti tipici">','<a class="card-button" href="prodotti.html">').replace('</p></div></button></article>','</p></div></a></article>');
main=main.replace(/<img src="assets\/products.jpg"[^>]+>/,picture('products','Raccolta delle arance nell’azienda agricola Il Pago','','',storySizes));
main=main.replace('href="#territorio"','href="territorio.html"').replace(/<img src="assets\/coast.jpg"[^>]+>/,picture('matera','I Sassi di Matera, da visitare durante il soggiorno','','','(max-width: 760px) max(100vw, 120svh), 100vw'));
let horizontal=main.match(/<section class="experiences section-pad"[\s\S]*?<\/section>/)[0];
main=main.replace(horizontal,'');
// A single canopy stays with the visitor from the garden into the horizontal chapters.
const experienceNavigation=horizontal.match(/<div class="experience-navigation">[\s\S]*?<span class="experience-scroll-hint[\s\S]*?<\/span><\/div>/)[0];
horizontal=horizontal.replace(experienceNavigation,'').replace(/^[\t ]+$/gm,'');
const canopy=gardenCanopy(experienceNavigation);
main=main.replace(passage,`<div class="nature-journey">${canopy}${passage}
${horizontal}</div>`);
// After the family story, white and clouds reveal the coast; table and rooms follow.
const rooms=main.match(/<section class="rooms section-pad"[\s\S]*?<\/section>/)[0];const table=main.match(/<section class="table-section"[\s\S]*?<\/section>/)[0];
main=main.replace(rooms,'').replace(table,table+'\n'+rooms);
const coast=coastalScene(picture, arrow);
main=main.replace(/<section class="territory"[\s\S]*?<\/section>/,'');
const storySection=main.match(/<section class="story section-pad"[\s\S]*?<\/section>/)[0];
main=main.replace(storySection,storySection+'\n'+coast);
main=main.replace('</main>',showcaseScene(picture,arrow)+'</main>');
main=main.replace(/^[\t ]+$/gm,'');
await write('index.html',`${head('La tua casa fuori casa','Il Pago, agriturismo a Rotondella. Camere nel verde, cucina lucana, fattoria e esperienze, a 4,5 km dal mare Jonio.','courtyard',true)}<body class="chrome-dark"><a class="skip-link" href="#main">Vai al contenuto</a>${svg}${common()}${noScript}<div class="journey-progress" aria-hidden="true"><span data-scroll-percent>00</span><span class="journey-line"><i></i></span><span class="journey-label">Il tuo tempo</span></div>${main}${pageFooter()}${dialogs}</body></html>`);
const simple=(title,body)=>`${head(title,title+' · Agriturismo Il Pago a Rotondella')}<body class="editorial-page simple-page"><a class="skip-link" href="#main">Vai al contenuto</a>${svg}${common(true)}${noScript}<main id="main" tabindex="-1" class="section-pad simple-content">${body}</main>${pageFooter(true)}${title==='Contatti'?menu+booking:dialogs}</body></html>`;
await write('contatti.html',simple('Contatti',`<div class="contact-panel">${contactBody.replace('<h2 ','<h1 ').replace('</h2>','</h1>')}</div>`));
await write('privacy.html',simple('Privacy',`<span class="micro">Il Pago · Informazioni</span><h1 class="display">La tua <span class="script">privacy.</span></h1><div class="privacy-copy"><p>Questo sito non usa strumenti di analisi, cookie di profilazione o contenuti incorporati da servizi esterni. La preferenza giorno/notte viene conservata nel localStorage del browser e puoi eliminarla cancellando i dati del sito.</p><p>Il modulo prepara un messaggio: nome, telefono, date e testo restano nel browser finché scegli di continuare su WhatsApp. Da quel momento il servizio esterno riceve i dati necessari a comporre il messaggio; l’invio avviene con una tua azione in WhatsApp. Il sito non salva i campi in un proprio database e non conferma prenotazioni.</p><p>Telefono, email, indicazioni e motore di prenotazione aprono i rispettivi servizi solo quando li selezioni. Per il trattamento dei dati da parte dell’Azienda agrituristica Il Pago, consulta <a class="text-link" href="https://www.ilpago.eu/images/privacy-policy.pdf" target="_blank" rel="noopener">l’informativa ufficiale ↗</a> oppure scrivi a <a href="mailto:info@ilpago.eu">info@ilpago.eu</a>.</p><a class="text-link" href="contatti.html" data-contact>Contatta Il Pago ${arrow}</a></div>`));
console.log('Built homepage, 8 editorial pages, contacts fallback and privacy.');
